[package]
name = "ferment"
version = "0.2.9"
edition = "2021"
license = "MIT"
description = "Traits for FFI conversions and some helper methods"

[dependencies]
indexmap = { version = "2.0.2", features = ["serde"] }
serde_json = { version = "1.0.96" }

[lib]
name = "ferment"
